/**
 * Artistic look presets — full UI state snapshots.
 * Reusable shape: applyLookPreset(ui, key) writes slider/select values, then call applyUi().
 */
export const LOOK_PRESETS = {
  studio: {
    label: 'Studio clean',
    note: 'baseline optical study',
    values: {
      preset: 'crystal',
      dispersion: 1.55,
      thickness: 1.9,
      ior: 1.85,
      roughness: 0.018,
      translucency: 0.08,
      speckle: 0.28,
      bloom: 0.34,
      glare: 0.35,
      flare: 0.25,
      dof: 0,
      dofFocus: 4.8,
      ascii: 0,
      asciiCell: 10,
      halftone: 0,
      afterimage: 0,
      caustics: 0.45,
      chroma: 0.7,
      vignette: 0.26,
      grain: 0.35,
      exposure: 1.08,
      dpr: 2,
      transmissionScale: 1,
      tonemap: 'aces',
    },
  },
  anamorphic: {
    label: 'Anamorphic cinema',
    note: 'horizontal glare · flare · vignette',
    values: {
      preset: 'flint',
      dispersion: 1.35,
      thickness: 1.85,
      ior: 1.62,
      roughness: 0.02,
      translucency: 0.1,
      speckle: 0.4,
      bloom: 0.72,
      glare: 1.15,
      flare: 0.85,
      dof: 0.22,
      dofFocus: 4.6,
      ascii: 0,
      asciiCell: 10,
      halftone: 0,
      afterimage: 0.12,
      caustics: 0.7,
      chroma: 1.05,
      vignette: 0.55,
      grain: 0.55,
      exposure: 1.15,
      dpr: 2,
      transmissionScale: 1,
      tonemap: 'aces',
    },
  },
  portrait: {
    label: 'Soft portrait',
    note: 'shallow DoF · gentle bloom',
    values: {
      preset: 'glass',
      dispersion: 0.65,
      thickness: 1.55,
      ior: 1.52,
      roughness: 0.04,
      translucency: 0.18,
      speckle: 0.15,
      bloom: 0.48,
      glare: 0.2,
      flare: 0.08,
      dof: 0.62,
      dofFocus: 4.9,
      ascii: 0,
      asciiCell: 10,
      halftone: 0,
      afterimage: 0,
      caustics: 0.25,
      chroma: 0.35,
      vignette: 0.4,
      grain: 0.22,
      exposure: 1.02,
      dpr: 2,
      transmissionScale: 1,
      tonemap: 'cineon',
    },
  },
  neonAscii: {
    label: 'Neon ASCII',
    note: 'grayscale ASCII cube · geometry hidden',
    values: {
      preset: 'crystal',
      dispersion: 1.9,
      thickness: 2.1,
      ior: 1.9,
      roughness: 0.015,
      translucency: 0.06,
      speckle: 0.55,
      bloom: 0.55,
      glare: 0.25,
      flare: 0.15,
      dof: 0,
      dofFocus: 4.8,
      ascii: 1,
      asciiCell: 8,
      halftone: 0,
      afterimage: 0,
      caustics: 0.85,
      chroma: 0.55,
      vignette: 0.15,
      grain: 0.08,
      exposure: 1.15,
      dpr: 2,
      transmissionScale: 1,
      tonemap: 'aces',
    },
  },
  ghostTrail: {
    label: 'Ghost trail',
    note: 'long afterimage · spectral smear',
    values: {
      preset: 'flint',
      dispersion: 1.7,
      thickness: 1.9,
      ior: 1.7,
      roughness: 0.02,
      translucency: 0.12,
      speckle: 0.35,
      bloom: 0.6,
      glare: 0.7,
      flare: 0.45,
      dof: 0.15,
      dofFocus: 5.0,
      ascii: 0,
      asciiCell: 10,
      halftone: 0,
      afterimage: 0.82,
      caustics: 0.65,
      chroma: 0.9,
      vignette: 0.3,
      grain: 0.4,
      exposure: 1.1,
      dpr: 2,
      transmissionScale: 1,
      tonemap: 'aces',
    },
  },
  printShop: {
    label: 'Print shop',
    note: 'CMYK halftone · editorial',
    values: {
      preset: 'glass',
      dispersion: 0.9,
      thickness: 1.7,
      ior: 1.55,
      roughness: 0.03,
      translucency: 0.14,
      speckle: 0.2,
      bloom: 0.28,
      glare: 0.15,
      flare: 0.05,
      dof: 0.1,
      dofFocus: 4.7,
      ascii: 0,
      asciiCell: 10,
      halftone: 0.85,
      afterimage: 0,
      caustics: 0.3,
      chroma: 0.25,
      vignette: 0.2,
      grain: 0.5,
      exposure: 1.05,
      dpr: 2,
      transmissionScale: 0.85,
      tonemap: 'reinhard',
    },
  },
  prismChaos: {
    label: 'Prism chaos',
    note: 'everything on · art-directed overload',
    values: {
      preset: 'crystal',
      dispersion: 2.2,
      thickness: 2.2,
      ior: 2.05,
      roughness: 0.012,
      translucency: 0.05,
      speckle: 0.75,
      bloom: 1.05,
      glare: 1.0,
      flare: 0.95,
      dof: 0.28,
      dofFocus: 4.5,
      ascii: 1,
      asciiCell: 10,
      halftone: 0.25,
      afterimage: 0.35,
      caustics: 1,
      chroma: 1.35,
      vignette: 0.45,
      grain: 0.6,
      exposure: 1.25,
      dpr: 2,
      transmissionScale: 1,
      tonemap: 'aces',
    },
  },
}

/** Maps look-preset value keys → UI element ids / property names on the ui object. */
export const LOOK_UI_KEYS = {
  preset: 'preset',
  dispersion: 'dispersion',
  thickness: 'thickness',
  ior: 'ior',
  roughness: 'roughness',
  translucency: 'translucency',
  speckle: 'speckle',
  bloom: 'bloom',
  glare: 'glare',
  flare: 'flare',
  dof: 'dof',
  dofFocus: 'dofFocus',
  ascii: 'ascii',
  asciiCell: 'asciiCell',
  halftone: 'halftone',
  afterimage: 'afterimage',
  caustics: 'caustics',
  chroma: 'chroma',
  vignette: 'vignette',
  grain: 'grain',
  exposure: 'exposure',
  envIntensity: 'envIntensity',
  dpr: 'dpr',
  transmissionScale: 'transmissionScale',
  tonemap: 'tonemap',
}

/**
 * Writes a look preset into DOM controls.
 * @param {Record<string, HTMLElement>} ui
 * @param {string} key
 * @returns {boolean}
 */
export function applyLookPreset(ui, key) {
  const look = LOOK_PRESETS[key]
  if (!look) return false

  for (const [valueKey, uiKey] of Object.entries(LOOK_UI_KEYS)) {
    const el = ui[uiKey]
    const value = look.values[valueKey]
    if (!el || value === undefined) continue
    el.value = String(value)
  }

  if (ui.lookNote) ui.lookNote.textContent = look.note
  return true
}
